### PR TITLE
assert added for custom labels

### LINKED ISSUE #116: [CustomLabels] : CustomLabels Throws Error When Single Label Passed at 0 value
## BUG:  `CustomLabels` Throws Error When Single `customLabel` is passed at 0 value
Screenshot 2023-03-20 at 12 14 34 PM

### Steps to Reproduce:
```Dart
LinearGauge(
          start: 0,
          end: 100,
          customLabels: [CustomRulerLabel(text: "Custom", value: 0)],
          rulers: RulerStyle(rulerPosition: RulerPosition.bottom),
        ),
```

### Environment:
Version : `0.1`

### Additonal Information

- This issue occurs in both GaugeOrientations
- The issue occurs consistently across different devices and browsers.

### PR DESCRIPTION
**Pull request by SahilSharma2710**
fixes #116 

Assert has been added to add atleast two custom labels and first custom label value should be less than last

### CODE REVIEW

File: lib/linear_gauge/linear_gauge.dart [hunk 1]
```diff
@@ -39,6 +39,15 @@ class LinearGauge extends StatefulWidget {
     this.enableAnimation = false,
     this.extendLinearGauge = 0,
   })  : assert(() {
+          if (customLabels!.isNotEmpty) {
+            if (customLabels.length < 2) {
```
Comment (hasnentai) [inline lib/linear_gauge/linear_gauge.dart:43]: Remove if from here and write it in assert

File: lib/linear_gauge/linear_gauge.dart [hunk 2]
```diff
@@ -39,6 +39,15 @@ class LinearGauge extends StatefulWidget {
...
+              assert(false, "At least two CustomRulerLabel should be added");
+            }
+
+            if (customLabels.first.value! > customLabels.last.value!) {
+              assert(false, "Start should be less then end");
```
Comment (hasnentai) [inline lib/linear_gauge/linear_gauge.dart:48]: remove if and write in assert

**Review by hasnentai — CHANGES_REQUESTED** [review]

**Review by hasnentai — APPROVED** [review]
